### PR TITLE
Fixed Recursive References

### PR DESCRIPTION
**Pull request by Levirclark**
Users have been mentioning that recursive references are still a problem.
Setting cell a1 to the value '=A1' will crash the application.
This fixes that, by scanning for recursive references prior to attempting a render.

### CODE REVIEW

**Comment by sain2424** [comment]
This already works. Demo isn't updated.

**Comment by Levirclark** [comment]
It's not working if you follow the dev process

git clone https://github.com/myliang/x-spreadsheet.git
cd x-spreadsheet
npm install
npm run dev

Should it be working on local dev servers?

**Comment by Levirclark** [comment]
> This already works. Demo isn't updated.

**Comment by Levirclark** [comment]
Kkk

**Comment by myliang** [comment]
@Levirclark thx, good code

**Pull request closed without merging**
