### PR TITLE
Paste from clipboard

### PR DESCRIPTION
**Pull request by anhvutnu**
Hello,
This is my attempt to add supporting for pasting content from system clipboard. Please let me know what you think.

### CODE REVIEW

**Comment by MartinDawson** [comment]
@anhvutnu This handles text content nicely. How can we also do colors and styles like google sheets does?

**Comment by ThibautSF** [comment]
@anhvutnu Thanks for the PR, unfortunately looks like that FireFox doesn't support [navigator.clipboard.readText()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#clipboard_availability) yet.
Throw `Uncaught TypeError: navigator.clipboard.readText is not a function`
So I made some minor modifications in the following pull request against your fork : https://github.com/anhvutnu/x-spreadsheet/pull/1

**Comment by ohechtl** [comment]
Hey, what is the status of this PR?

**Comment by coderhn** [comment]
感谢大佬填坑！

**Pull request merged**
