### PR TITLE
fix some ESlint error and improve Mac/Win touchpad horizontal scroll and mouse shift-wheel effect

### PR DESCRIPTION
**Pull request by Jonham**
1. fix some ESlint error
2. improve Mac/Win touchpad horizontal scroll and mouse shift-wheel effect

and I've try to add `pre-commit` to excute "yarn lint" and "yarn test" whenever commit to git.
but, `pre-commit` somehow slow down each commit even there is no error.
so finally I removed it.
maybe we should find another better way to keep code lint and clean.

### CODE REVIEW

**Comment by Jonham** [comment]
cov decrease ??

**Comment by Jonham** [comment]
confusing

image

**Comment by Jonham** [comment]
@myliang 这个应该可以merge。
或者有什么顾虑，这个地方改进了 横向滚动的问题。让滚动更自然些。

**Comment by Jonham** [comment]
另外，我现在基于我自己的分支，改了很多内容（较多是定制性的）。
有没有可以看特性或者整体方案的地方。我可以把部分需要的、规划内的功能PR过来。

**Comment by myliang** [comment]
建议每个修改都分开吧，对新功能咱不考虑添加，bug可以merge

**Comment by Jonham** [comment]
OK

**Pull request closed without merging**
